<?php

namespace DoctrineMongoODMModule\Hydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class ApplicationDocumentUserHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="custom_id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['username'])) {
            $value = $data['username'];
            $return = (string) $value;
            $this->class->reflFields['username']->setValue($document, $return);
            $hydratedData['username'] = $return;
        }

        /** @ReferenceOne */
        if (isset($data['item'])) {
            $reference = $data['item'];
            if (isset($this->class->fieldMappings['item']['simple']) && $this->class->fieldMappings['item']['simple']) {
                $className = $this->class->fieldMappings['item']['targetDocument'];
                $mongoId = $reference;
            } else {
                $className = $this->dm->getClassNameFromDiscriminatorValue($this->class->fieldMappings['item'], $reference);
                $mongoId = $reference['$id'];
            }
            $targetMetadata = $this->dm->getClassMetadata($className);
            $id = $targetMetadata->getPHPIdentifierValue($mongoId);
            $return = $this->dm->getReference($className, $id);
            $this->class->reflFields['item']->setValue($document, $return);
            $hydratedData['item'] = $return;
        }

        /** @Field(type="boolean") */
        if (isset($data['isOnline'])) {
            $value = $data['isOnline'];
            $return = (bool) $value;
            $this->class->reflFields['isOnline']->setValue($document, $return);
            $hydratedData['isOnline'] = $return;
        }

        /** @Field(type="date") */
        if (isset($data['lastUpdated'])) {
            $value = $data['lastUpdated'];
            if ($value instanceof \MongoDate) { $return = new \DateTime(); $return->setTimestamp($value->sec); } elseif (is_numeric($value)) { $return = new \DateTime(); $return->setTimestamp($value); } else { $return = new \DateTime($value); }
            $this->class->reflFields['lastUpdated']->setValue($document, clone $return);
            $hydratedData['lastUpdated'] = $return;
        }

        /** @Field(type="float") */
        if (isset($data['postionX'])) {
            $value = $data['postionX'];
            $return = (float) $value;
            $this->class->reflFields['postionX']->setValue($document, $return);
            $hydratedData['postionX'] = $return;
        }

        /** @Field(type="float") */
        if (isset($data['postionY'])) {
            $value = $data['postionY'];
            $return = (float) $value;
            $this->class->reflFields['postionY']->setValue($document, $return);
            $hydratedData['postionY'] = $return;
        }

        /** @Field(type="float") */
        if (isset($data['postionZ'])) {
            $value = $data['postionZ'];
            $return = (float) $value;
            $this->class->reflFields['postionZ']->setValue($document, $return);
            $hydratedData['postionZ'] = $return;
        }
        return $hydratedData;
    }
}