<?php

namespace DoctrineMongoODMModule\Hydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class ApplicationDocumentItemHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="custom_id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['name'])) {
            $value = $data['name'];
            $return = (string) $value;
            $this->class->reflFields['name']->setValue($document, $return);
            $hydratedData['name'] = $return;
        }

        /** @Field(type="float") */
        if (isset($data['postionX'])) {
            $value = $data['postionX'];
            $return = (float) $value;
            $this->class->reflFields['postionX']->setValue($document, $return);
            $hydratedData['postionX'] = $return;
        }

        /** @Field(type="float") */
        if (isset($data['postionY'])) {
            $value = $data['postionY'];
            $return = (float) $value;
            $this->class->reflFields['postionY']->setValue($document, $return);
            $hydratedData['postionY'] = $return;
        }

        /** @Field(type="float") */
        if (isset($data['postionZ'])) {
            $value = $data['postionZ'];
            $return = (float) $value;
            $this->class->reflFields['postionZ']->setValue($document, $return);
            $hydratedData['postionZ'] = $return;
        }
        return $hydratedData;
    }
}