<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
$env = getenv('APP_ENV') ?: 'production';

return array(
    'modules' => array(
        'DoctrineModule',
        'DoctrineMongoODMModule',
        'Application',
        'Api'
        ),
    'module_listener_options' => array(
        'module_paths' => array(
            './core/module',
            './core/vendor'
            ),
        'config_glob_paths' => array(sprintf('%s/config/autoload/{,*.}{global,%s,local}.php', dirname(__DIR__), $env))
        )
    );
