<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>House</title>
 
<link rel="stylesheet" href="/css/main.css" type="text/css" />
 
</head>
 
<body id="index" class="home">
 <?php echo $this->content; ?>
</body>

<script src="/js/vendor/tquery/tquery-bundle-require.min.js"></script>
<script src="/js/vendor/jquery-2.0.3.min.js"></script>
<script src="/js/app.js"></script>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-25126145-1']);
  _gaq.push(['_setDomainName', 'miguelpz.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</html>